MyAccountDropDown = "xpath:(//a[@id ='dropdownCurrency'])[2]"
SignUpLink = "xpath://a[text() ='Sign Up']"
FirstNameInput = "name:firstname"
LastNameInput = "name:lastname"
MobileInput = "name:phone"
EmailInput = "name:email"
PasswordInput = "name:password"
ConfirmPasswordInput = "name:confirmpassword"
SignUpButton = "xpath://button[text() =' Sign Up']"
LoginLink = "xpath://a[text() ='Login']"
UsernameInput = "name:username"
LoginButton = "xpath://button[text() ='Login']"
HomeLogoImage = "xpath://div[@class ='header-logo go-right']//a//img"
LogoutLink = "xpath://a[text() ='Logout']"
AdultPlusButton = "xpath:(//input[@name ='%s%'])[1]//..//span/button[text() ='+']"
AdultMinusButton = "xpath:(//input[@name ='%s%'])[1]//..//span/button[text() ='-']"
AdultsInput = "xpath:(//input[@name ='%s%'])[1]"
LoginLabel = "xpath://h3[text() ='Login']"
HotelNavTab = "xpath://nav[@class ='menu-horizontal-02']//a[contains(text(),'Hotel')]"
SearchLabelInput = "xpath:(//span[text()='Search by Hotel or City Name'])[1]"
SearchInput = "xpath://div[@id ='select2-drop']//div//input"
SearchListView = "xpath://div[@id ='select2-drop']//ul[@class ='select2-results']//li"
SearchButton = "xpath://div[@id ='hotels']//button[contains(text(),'Search')]"
SearchListedValue = "xpath://ul[@class='select2-result-sub']//span[contains(text(),'%s%')]"
CheckOutDateInput = "xpath://input[@id ='checkout']"
CheckInDateInput = "xpath://input[@id ='checkin']"
DatePickerTitle = "xpath://div[@id='datepickers-container']//div[%s%]//nav[1]//div[@class='datepicker--nav-title']"
DatePickerYear = "xpath://div[@id='datepickers-container']//div[%s%]//div[contains(@class,'datepicker--cell " \
                 "datepicker--cell-year')][@data-year='${year}'] "
DatePickerNextButton = "xpath://div[@id='datepickers-container']//div[%s%]//div[contains(@class," \
                       "'datepicker--nav-action')][@data-action='next'] "
DatePickerMonth = "xpath://div[@id='datepickers-container']//div[$s%]//div[@class='datepicker--cell " \
                  "datepicker--cell-month'][@data-month='${month}'] "
DatePickerDays = "xpath://div[@id='datepickers-container']//div[%s%]//div[contains(@class,'datepicker--cell " \
                 "datepicker--cell-day')][@data-date='${day}'][@data-month='${month}'] "


